ourproject/myapp/urls.py
# from .models import Product
from django.urls import path
from .views import item, showbrand, one_item, filtered_product, ProductView, oneProductView, createOneProductView, updateOneProductView

app_name  = "myapp"

urlpatterns = [
    #normal endpoints
    path("brand/",showBrand,name="showbrand"),
    path("items/",showProduct,name="showproduct"),
    path("filter/",filtered_product,name="filterproducts"),
    path("product/<int:id>/",one_product,name="showoneproduct"),
    path("",index,name="name"),

    #Api endpoints
    path("productView/", ProductView, name="Product_view"),
    path("oneProductView/<int:id>", oneProductView, name="Product_view"),
    path("oneProductView/create/", createOneProductView, name="Product_view"),
    path("updateOneProductView/<int:id>", updateOneProductView, name="Product_view"),
    path("deleteOneProductView/<int:id>", deleteOneProductView, name="Product_view")
    ]

ourproject/ourproject/urls.py
from django.contrib import admin
from django.urls import path, include
#from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("myapp.urls")),
    path('api-auth/', include('rest_framework.urls'))
    
]

ourproject/myapp/models.py
from django.db import models

class Product(models.Model):
    Quality = [
        ('brand_new','brand_new'),
        ('good','good'),
        ('average','average'),
        ('bad','bad')
    ]
    name = models.CharField(max_length= 250)
    price = models.PositiveIntegerField()
    image = models.ImageField()
    quality = models.CharField(max_length = 250, choices = Quality)
    description = models.TextField()
    
    def __str__(self):
        return self.name+" "+str(self.price)

    class Meta:
        ordering = ['price']

class Brand(models.Model):
    brand_name = models.CharField(max_length = 250)
    brand_logo = models.ImageField()
    brand_description = models.TextField()
    brand_moto = models.SlugField(max_length=50)

    def __str__(self):
        return self.brand_name

    class Meta:
        ordering = ['brand_name']


# class testing(models.Model):
#     firstName = models.CharField(max_length=250)
#     num = models.IntegerField()
#     def __str__(self):
#         return self.firstName

# #One to one
# class Home(models.Model):
#     Home = models.CharField(max_length=250)
#     def __str__(self):
#         return self.Home
# class Family(models.Model):
#     family_name =  models.CharField(max_length=250)
#     home = models.OneToOneField(Home, on_delete=models.SET_NULL, null=True)
#     def __str__(self):
#         return self.family_name

# #one to one
# class Room(models.Model):
#     room = models.IntegerField()
# class Person(models.Model):
#     totalPerson =  models.IntegerField()
#     Room = models.OneToOneField(Room, on_delete=models.CASCADE)

# #one to many
# class Parents(models.Model):
#     parents_cast = models.CharField(max_length=250)
#     def __str__(self):
#         return self.parents_cast
# class Children(models.Model):
#     child_name = models.CharField(max_length=250)
#     belongs_to = models.ForeignKey(Parents,on_delete=models.CASCADE, null=True)
#     def __str__(self):
#         return self.child_name

# #many to many
# class Item(models.Model):         
#     name = models.CharField(max_length=200)
#     def __str__(self):
#         return self.name
# class Tag(models.Model):
#     tag_name = models.CharField(max_length=200)
#     tag_belongs_to = models.ManyToManyField(Item) # , on_delete=models.SET_NULL, null=True
#     def __str__(self):
#         return self.tag_name

ourproject/myapp/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from .models import *
from .models import Product
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import ProductViewSet, OneProductViewSet

@api_view(['GET'])
def ProductView(request):
    query_set = Product.objects.all().order_by("-id")
    sterilized = ProductViewSet (query_set, many=True)
    return Response(sterilized.data)

@api_view(['GET'])
def ProductView(request):
    query_set = Product.objects.get(id =id)
    sterilized = OneProductViewSet (query_set, many=False)
    return Response(sterilized.data)

@api_view(['POST'])
def createOneProductView (request):
    serialized = OneProductViewSet(data=request.data)
    if serialized.is_valid():
        serialized.save()
    else:
        print("Invlaid Data")
    return Response(serialized.data)

@api_view(['POST'])
def updateOneProductView(request, id):
    serialized = OneProductViewSet(instance=Product.objects.get(id=id), data=request.data) #instance specifies product
    if serialized.is_valid():
        serialized.save()
    else:
        print("Invlaid Data")
    return Response(serialized.data)

@api_view(['DELETE'])
def deleteOneProductView (request, id):
    Product.objects.get(id=id).delete()
    return Response("Deleted")



def index(request):
    return render(request, 'index.html')

def showProduct(request):
    get_data = Product.objects.all()  # get(brand_name="Apple")
    print(get_data)
    return render(request, 'index.html', {'data': get_data})

def one_product(request, id):
    get_one_data = Product.objects.get(id=id)
    return render(request, 'oneProduct.html', {'product_data': get_one_data})

def showBrand(request):
    get_data = Brand.objects.all()  # get(brand_name="Apple")
    return render(request, 'brand.html', {'brand_data': get_data})

def filtered_product(request):
    filtered_data = Product.objects.all()
    print(filtered_data)
    return render(request, 'filter.html', {'filter_data': filtered_data})



    # get_all_data = Product.objects.all().filter(price=client.id).order_by('check_in')
    # sorted_data = get_all_data.sort()

# def learn(request):
#     return HttpResponse("i am learning django")

    # one to one
    # a = Family.objects.get(home__Home ="Shrestha Niwas")
    # print(a)

    # one to many
    # a = Children.objects.get(belongs_to__parents_cast__startswith = "su")
    # print(a)

    # #create
    # testing.objects.create(firstName = "faran", num = 6)
    # return HttpResponse (f"hello {testing.firstName} {testing.num}")

    # get
    # testing1 = testing.objects.get(num = 1)
    # return HttpResponse (f"hello {testing1.firstName} {testing1.num}")

    # edit/update
    # testing2 = testing.objects.get(num = 2)
    # testing2.firstName = "bishwakarma"
    # testing2.save()
    # return HttpResponse (f"hello {testing2.num} {testing2.firstName}")

    # delete
    # testing3 = testing.objects.get(num = 3).delete() #testing3.delete()
    # return HttpResponse (f"hello")

    # get
    # testing3 = testing.objects.get(num = 3)
    # testing3.firstName = "ramayan"
    # return HttpResponse (f"hello {testing3.firstName}")

    # filter
    # testing4 = testing.objects.filter(firstName__startswith = "am")
    # print(testing4)
    # return HttpResponse (f"hello {testing4.firstName} {testing4.num}")

    # testing4 = testing.objects.filter(firstName__startswith = "am")
    # print(testing4)
    # return HttpResponse (f"hello")

ourproject/myapp/templates/brand.html
{% extends 'index.html' %}

{% block displayBrand %}
<h1>hello i am brand's template</h1>
{% for i in brand_data %}
{{ i.brand_name }}: {{ i.brand_moto }}: {{ i.brand_description }}<br>
{% endfor %}
{% endblock displayBrand %}

ourproject/myapp/templates/filter.html
{% extends 'index.html' %}

{% block filter %}

    {% for i in filter_data %}

<div class="card" style="width: 18rem;">
  <img src="https://picsum.photos/200/300" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ i.name }}</h5>
    <h5 class="card-title">{{ i.quality }}</h5>
    <h5 class="card-title">{{ i.price }}</h5>
    <p class="card-text">{{ i.description }}</p>
    {% comment %} <a href="{% url 'myapp:product' i.id %}" class="btn btn-primary">BUY</a> {% endcomment %}
  </div>
</div>

{% endfor %}

{% endblock filter %}

ourproject/myapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Demo One</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    <div class="d-flex" style="display: flex; justify-content : space-around">
    {% block product %} 
    
    {% endblock product %}
    </div>
    
    {% block displayBrand %}
    
    {%endblock displayBrand %} 

    {% block oneproduct %}
    
    {% endblock oneproduct %}

    {% block filter %}
    
    {% endblock filter %}

    {% comment %}
    <h1>{{data.brand_description}}</h1>
    <h1>{{data.brand_name}}</h1>
    <h1>{{data.brand_logo}}</h1>
    <h1>{{data.brand_moto}}</h1>
    {% endcomment %}

    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
      crossorigin="anonymous"></script>
    <script= {% static"index.js" %}></script>
  </body>
</html>

ourproject/myapp/templates/oneProduct.html
{% extends 'index.html' %}

{% block oneproduct %}
<div class="card">
  <div class="card-header">{{ product_data.name }}</div>
  <div class="card-body">
    <img src="https://picsum.photos/200/300" class="card-img-top" alt="...">
    <h5 class="card-title">{{ product_data.price }}</h5>
    <h5 class="card-title">{{ product_data.quality }}</h5>
    <p class="card-text">{{ product_data.description }}</p>
    <a href="#" class="btn btn-primary">BUY</a>
  </div>
</div>
{% endblock oneproduct %}

ourproject/myapp/templates/product.html
{% extends 'index.html' %}

{% block product %}
{% comment %} <h1>hello i am product's template</h1> {% endcomment %}

<a class="btn btn-primary btn-sm" href="{% url 'myapp:filterproducts'  %}">filter button</button>
  <br>
  {% for i in data %}

  <div class="card" style="width: 18rem;">
    <img src="https://picsum.photos/200/300" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{ i.name }}</h5>
      <h5 class="card-title">{{ i.quality }}</h5>
      <h5 class="card-title">{{ i.price }}</h5>
      <p class="card-text">{{ i.description }}</p>
      <a href="{% url 'myapp:showoneproduct' i.id %}" class="btn btn-primary">BUY</a>
    </div>
  </div>

  {% endfor %}

  {% endblock product %}

  {% comment %} {{ i.name }}: {`{ i.price }}: {{ i.quality }}<br> {% endcomment %}